### ISSUE TITLE
BUG: App threw an error during load

### ISSUE THREAD

**Issue by SaturnFiveLive** [wAIfu-DEV/w-AI-fu_v2#59]
**Describe the bug**
When launching, the following error is produced

App threw an error during load
TypeError: Cannot read properties of undefined (reading 'autoPong')
    at new WebSocket (C:\Users\User\Downloads\Vtuber\node_modules\ws\lib\websocket.js:87:32)
    at Object.<anonymous> (C:\Users\User\Downloads\Vtuber\source\app\closed_captions\stream_captions.js:30:28)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\User\Downloads\Vtuber\source\app\closed_captions\closed_captions.js:29:27)

**To Reproduce**
I followed the installation instructions
installing python 3.10.x, cuda 10.1 and build tools including desktop development.
Ran install.bat and attempted to launch the program.

**Expected behavior**
The program to launch
I checked the requirements.txt and manually checked that each module was installed.

**Screenshots**
<img width="785" alt="image" src="https://github.com/wAIfu-DEV/w-AI-fu_v2/assets/157905810/7fc03777-f575-44b8-8db6-f8832c1b65ba">

**Comment by xxandeer** [comment]
I understand the technical difference between the caret (^) and the exact
version, but I'm curious about the specific reason behind this change. Can
you explain what impact or difference you expect this modification to have
on the project or its dependencies?

**Comment by wAIfu-DEV** [comment]
new versions of the ws package introduced a bug that breaks compatibility with the expected behaviour, removing the `^` forces npm to install an older but working version.

**Comment by SaturnFiveLive** [comment]
Thank you
